[2022-10-13 08:11:34,683 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:37,798 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:38,860 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:40,048 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:40,488 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:40,794 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:41,250 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:42,294 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:43,364 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:44,954 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:46,011 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:46,660 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:46,780 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:47,104 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:48,129 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:49,322 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:50,355 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:51,375 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:52,419 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:52,532 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:52,732 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:53,512 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:54,528 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:55,532 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:56,790 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:58,011 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:11:58,372 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:58,532 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:11:59,241 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:00,879 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:01,974 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:03,223 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:04,308 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:04,516 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:04,564 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:05,383 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:06,481 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:07,715 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:09,041 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:10,135 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:10,694 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:10,766 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:11,359 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:11,579 | tradestation:345 | WARNING | MainProcess] Failed getting balance: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 316, in get_balances
    query = self.ts_client.get_balances(account_keys=[self.account_name])
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 814, in get_balances
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 533, in _handle_requests
    response = requests.get(url=url, headers=headers, params=params, verify=True)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\util\ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:12:12,390 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in check_buy
    quantity = random.randomint(0, 3)
AttributeError: module 'random' has no attribute 'randomint'
[2022-10-13 08:12:23,710 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:26,622 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:27,671 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:28,920 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:29,305 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:29,529 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:30,042 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:31,188 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:32,185 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:33,224 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:34,259 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:35,240 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:35,312 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:35,521 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:36,603 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:37,641 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:38,665 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:39,704 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:40,699 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:41,280 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:41,674 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:41,962 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:43,000 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:44,045 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:45,036 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:46,074 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:47,098 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:47,314 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:47,514 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:48,203 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:49,415 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:50,462 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:51,510 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:52,540 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:53,244 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:53,608 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:53,656 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:12:54,816 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:55,878 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:56,945 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:57,936 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 445, in check_buy
    threshold = random.unifrom(0, 1/3)
AttributeError: module 'random' has no attribute 'unifrom'
[2022-10-13 08:12:58,866 | tradestation:435 | WARNING | MainProcess] Failed getting positions: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 411, in get_positions
    query = self.ts_client.get_positions(account_keys=[self.account_name])
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 1054, in get_positions
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 526, in _handle_requests
    self._token_validation()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 448, in _token_validation
    self._grab_refresh_token()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 350, in _grab_refresh_token
    response = requests.post(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:13:33,373 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:36,117 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 440, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 487, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:13:37,130 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:38,137 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:39,100 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:13:39,156 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:13:39,244 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:40,716 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:41,768 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:42,755 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:43,798 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:44,901 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 440, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 487, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:13:45,629 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:13:45,816 | backend:557 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 553, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 348, in synchronize_broker_with_db
    open_trades = self.trade_history[self.trade_history.status.isin(["own", "sell_ordered", "sell_order_received"])]
AttributeError: 'Backend' object has no attribute 'trade_history'
[2022-10-13 08:13:45,944 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:47,007 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:48,155 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 440, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 487, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:13:49,172 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:13:50,161 | backend:644 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 638, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 450, in check_buy
    f'\n\t final trade budget: {trade_budget}'
NameError: name 'trade_budget' is not defined
[2022-10-13 08:14:19,855 | backend:449 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $137.41/share
[2022-10-13 08:14:22,131 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 08:14:25,295 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:14:25,403 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:14:26,440 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:26,440 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:26,473 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:27,940 | backend:449 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $137.48/share
[2022-10-13 08:14:29,052 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-13 08:14:32,260 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:32,974 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:33,265 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 440, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 485, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:14:33,433 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:34,318 | backend:449 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $137.5/share
[2022-10-13 08:14:35,339 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 08:14:38,843 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:39,576 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:39,865 | backend:449 | INFO | MainProcess] Attempting to buy 1 shares of ABBV at $138.53/share
[2022-10-13 08:14:40,060 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:40,828 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABBV ordered
[2022-10-13 08:14:43,879 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:45,072 | backend:449 | INFO | MainProcess] Attempting to buy 2 shares of ABC at $138.18/share
[2022-10-13 08:14:45,614 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:46,227 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABC ordered
[2022-10-13 08:14:46,604 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:50,036 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:51,047 | backend:449 | INFO | MainProcess] Attempting to buy 1 shares of ABC at $138.23/share
[2022-10-13 08:14:51,726 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:52,043 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABC ordered
[2022-10-13 08:14:53,034 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:55,427 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:14:56,505 | backend:449 | INFO | MainProcess] Attempting to buy 1 shares of ADI at $139.11/share
[2022-10-13 08:14:57,732 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ADI ordered
[2022-10-13 08:14:57,948 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:14:59,628 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:15:01,633 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:15:04,325 | backend:449 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $213.66/share
[2022-10-13 08:15:04,798 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:15:05,314 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 08:15:07,968 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:15:08,688 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:15:09,683 | backend:449 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $137.72/share
[2022-10-13 08:15:10,690 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-13 08:15:10,827 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:15:13,785 | backend:555 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 551, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 196, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:15:14,569 | backend:642 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 636, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 437, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 464, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
AttributeError: 'Backend' object has no attribute 'order_history'
[2022-10-13 08:15:14,806 | tradestation:345 | WARNING | MainProcess] Failed getting balance: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 316, in get_balances
    query = self.ts_client.get_balances(account_keys=[self.account_name])
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 814, in get_balances
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 533, in _handle_requests
    response = requests.get(url=url, headers=headers, params=params, verify=True)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\NUC USER\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:17:42,781 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:18:17,178 | backend:453 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.44/share
[2022-10-13 08:18:19,118 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-13 08:18:22,177 | backend:646 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 640, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 441, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 468, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 1724, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 2031, in _setitem_with_indexer_missing
    self.obj._mgr = self.obj.append(value)._mgr
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\frame.py", line 8965, in append
    concat(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\reshape\concat.py", line 307, in concat
    return op.get_result()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\reshape\concat.py", line 532, in get_result
    new_data = concatenate_managers(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 226, in concatenate_managers
    values = _concatenate_join_units(join_units, concat_axis, copy=copy)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 490, in _concatenate_join_units
    to_concat = [
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 491, in <listcomp>
    ju.get_reindexed_values(empty_dtype=empty_dtype, upcasted_na=upcasted_na)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 423, in get_reindexed_values
    i8values = np.full(self.shape, fill_value.value)
AttributeError: 'NoneType' object has no attribute 'value'
[2022-10-13 08:18:23,023 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:18:23,256 | backend:646 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 640, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 489, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:18:23,368 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:18:24,516 | backend:646 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 640, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 489, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:18:25,510 | backend:646 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 640, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 444, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 489, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:18:26,287 | tradestation:402 | WARNING | MainProcess] Failed getting orders: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 354, in get_orders
    query = self.ts_client.get_historical_orders(account_keys=[self.account_name], since=14)
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 944, in get_historical_orders
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 526, in _handle_requests
    self._token_validation()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 448, in _token_validation
    self._grab_refresh_token()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 350, in _grab_refresh_token
    response = requests.post(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:20:37,652 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:21:11,115 | backend:453 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $98.76/share
[2022-10-13 08:21:12,735 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 08:21:16,139 | backend:646 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 640, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 441, in trade
    quantity_bought = self.check_buy(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 468, in check_buy
    self.order_history.loc[order_id] = [symbol, quantity, "buy", None, curr_time, None, curr_price, status]
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 1724, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\indexing.py", line 2031, in _setitem_with_indexer_missing
    self.obj._mgr = self.obj.append(value)._mgr
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\frame.py", line 8965, in append
    concat(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\reshape\concat.py", line 307, in concat
    return op.get_result()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\reshape\concat.py", line 532, in get_result
    new_data = concatenate_managers(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 226, in concatenate_managers
    values = _concatenate_join_units(join_units, concat_axis, copy=copy)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 490, in _concatenate_join_units
    to_concat = [
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 491, in <listcomp>
    ju.get_reindexed_values(empty_dtype=empty_dtype, upcasted_na=upcasted_na)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\pandas\core\internals\concat.py", line 423, in get_reindexed_values
    i8values = np.full(self.shape, fill_value.value)
AttributeError: 'NoneType' object has no attribute 'value'
[2022-10-13 08:21:17,038 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:21:17,086 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:\Users\NUC USER\Menaiot\stock_model\backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:21:17,182 | backend:453 | INFO | MainProcess] Attempting to buy 2 shares of A at $126.7/share
[2022-10-13 08:21:18,390 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-13 08:21:20,410 | tradestation:402 | WARNING | MainProcess] Failed getting orders: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 354, in get_orders
    query = self.ts_client.get_historical_orders(account_keys=[self.account_name], since=14)
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 944, in get_historical_orders
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 526, in _handle_requests
    self._token_validation()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 448, in _token_validation
    self._grab_refresh_token()
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 350, in _grab_refresh_token
    response = requests.post(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\util\ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:22:12,725 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:22:50,987 | backend:453 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $141.9/share
[2022-10-13 08:22:52,189 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-13 08:23:27,587 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:28,535 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:33,955 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:34,940 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:40,315 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:41,376 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:47,147 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:48,079 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:53,747 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:23:54,801 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:01,277 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:03,291 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:09,853 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:10,407 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:16,760 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:17,088 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:23,416 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:23,792 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:30,052 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:30,605 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:36,804 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:37,175 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:43,108 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:43,703 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:49,544 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:50,086 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:56,179 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:24:56,360 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:04,332 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:04,476 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:11,096 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:11,096 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:17,940 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:18,429 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:24,507 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:25,076 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:31,071 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:32,568 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:37,809 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:39,447 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:44,300 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:46,037 | backend:559 | ERROR | MainProcess] Monitor Broker Crashed
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 555, in monitor_broker
    self.synchronize_broker_with_db()
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 200, in synchronize_broker_with_db
    symbol_latest_status = list(self.db.document(symbol).collection("trade_history").list_documents())[-1].get().to_dict()['status']
IndexError: list index out of range
[2022-10-13 08:25:48,951 | tradestation:345 | WARNING | MainProcess] Failed getting balance: attempt 0/5
Traceback (most recent call last):
  File "C:\Users\NUC USER\Menaiot\stock_model\tradestation.py", line 335, in get_balances
    bod_query = self.ts_client.get_balances_bod(account_keys=[self.account_name])
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 866, in get_balances_bod
    response = self._handle_requests(
  File "C:\Users\NUC USER\Menaiot\stock_model\Tradestation_python_api\ts\client.py", line 533, in _handle_requests
    response = requests.get(url=url, headers=headers, params=params, verify=True)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\NUC USER\Menaiot\stock_model\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TypeError: handle_exit() takes 0 positional arguments but 2 were given
[2022-10-13 08:27:01,305 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 08:27:39,909 | backend:645 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 639, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 443, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 488, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 08:27:45,167 | backend:452 | INFO | MainProcess] Attempting to buy 1 shares of ABC at $139.17/share
[2022-10-13 08:27:46,447 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABC ordered
[2022-10-13 12:38:10,977 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 12:38:16,638 | backend:178 | ERROR | MainProcess] Error reading Order History of ADBE:858584137
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:38:18,335 | backend:178 | ERROR | MainProcess] Error reading Order History of BLK:858619243
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:38:18,992 | backend:178 | ERROR | MainProcess] Error reading Order History of A:858646157
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:38:22,025 | backend:178 | ERROR | MainProcess] Error reading Order History of FCX:858757722
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:38:29,350 | backend:178 | ERROR | MainProcess] Error reading Order History of PYPL:858701055
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:38:46,968 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ABBV at $142.39/share
[2022-10-13 12:38:49,402 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABBV ordered
[2022-10-13 12:39:14,885 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.3/share
[2022-10-13 12:39:15,874 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:39:19,640 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of A at $127.86/share
[2022-10-13 12:39:20,609 | tradestation:489 | INFO | MainProcess] BUY 3 shares of A ordered
[2022-10-13 12:39:24,736 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $142.31/share
[2022-10-13 12:39:25,935 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-13 12:39:29,627 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ADI at $142.29/share
[2022-10-13 12:39:30,631 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ADI ordered
[2022-10-13 12:39:34,406 | backend:652 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 646, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 450, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 495, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 12:39:35,617 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of A at $127.86/share
[2022-10-13 12:39:36,565 | tradestation:489 | INFO | MainProcess] BUY 3 shares of A ordered
[2022-10-13 12:39:40,264 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ABC at $141.7/share
[2022-10-13 12:39:41,321 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABC ordered
[2022-10-13 12:39:45,364 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $99.01/share
[2022-10-13 12:39:46,416 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 12:39:50,219 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ADI at $142.34/share
[2022-10-13 12:39:51,183 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ADI ordered
[2022-10-13 12:39:55,154 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.58/share
[2022-10-13 12:39:56,139 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:40:01,004 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ABBV at $142.35/share
[2022-10-13 12:40:03,112 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABBV ordered
[2022-10-13 12:40:07,187 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $142.37/share
[2022-10-13 12:40:08,163 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 12:40:11,777 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $220.51/share
[2022-10-13 12:40:12,766 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-13 12:40:16,569 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.6/share
[2022-10-13 12:40:17,759 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:40:21,420 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $99.02/share
[2022-10-13 12:40:22,491 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 12:40:26,511 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $142.39/share
[2022-10-13 12:40:27,504 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-13 12:40:31,343 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $99.0/share
[2022-10-13 12:40:32,403 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 12:40:36,361 | backend:652 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 646, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 450, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 495, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 12:40:37,598 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.57/share
[2022-10-13 12:40:38,598 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:40:42,266 | backend:652 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 646, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 450, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 495, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 12:40:43,465 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $142.41/share
[2022-10-13 12:40:45,617 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-13 12:40:49,275 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of A at $127.79/share
[2022-10-13 12:40:50,253 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-13 12:40:53,979 | backend:652 | ERROR | MainProcess] Exception in stream quotes
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 646, in stream_quotes
    self.trade(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 450, in trade
    self.check_sell(symbol=symbol, curr_price=curr_price, curr_time=curr_time)
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 495, in check_sell
    if symbol in self.black_list:
AttributeError: 'Backend' object has no attribute 'black_list'
[2022-10-13 12:40:55,424 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of A at $127.79/share
[2022-10-13 12:40:56,386 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-13 12:41:00,886 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $98.99/share
[2022-10-13 12:41:02,921 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-13 12:41:11,214 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-13 12:41:16,394 | backend:178 | ERROR | MainProcess] Error reading Order History of ADBE:858584137
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:41:18,419 | backend:178 | ERROR | MainProcess] Error reading Order History of BLK:858619243
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:41:19,310 | backend:178 | ERROR | MainProcess] Error reading Order History of A:858646157
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:41:22,350 | backend:178 | ERROR | MainProcess] Error reading Order History of FCX:858757722
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:41:29,717 | backend:178 | ERROR | MainProcess] Error reading Order History of PYPL:858701055
Traceback (most recent call last):
  File "C:/Users/NUC USER/Menaiot/stock_model/backend.py", line 165, in get_document_info
    quantity = info["quantity"]
KeyError: 'quantity'
[2022-10-13 12:41:48,094 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $142.43/share
[2022-10-13 12:41:49,823 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-13 12:41:54,648 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of A at $127.79/share
[2022-10-13 12:41:55,576 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-13 12:41:59,156 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $142.59/share
[2022-10-13 12:42:01,119 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-13 12:42:05,324 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $98.98/share
[2022-10-13 12:42:06,310 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-13 12:42:09,921 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ABBV at $142.48/share
[2022-10-13 12:42:10,925 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABBV ordered
[2022-10-13 12:42:14,677 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ABC at $141.82/share
[2022-10-13 12:42:15,641 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ABC ordered
[2022-10-13 12:42:19,258 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $142.59/share
[2022-10-13 12:42:20,193 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-13 12:42:23,868 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.66/share
[2022-10-13 12:42:24,844 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:42:28,870 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ADI at $142.46/share
[2022-10-13 12:42:29,857 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ADI ordered
[2022-10-13 12:42:33,712 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $220.66/share
[2022-10-13 12:42:35,004 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-13 12:42:38,560 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $142.62/share
[2022-10-13 12:42:39,607 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 12:42:43,256 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $220.69/share
[2022-10-13 12:42:44,221 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-13 12:42:47,983 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $142.47/share
[2022-10-13 12:42:48,949 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-13 12:42:52,722 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $220.71/share
[2022-10-13 12:42:53,706 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-13 12:42:57,670 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $98.98/share
[2022-10-13 12:42:58,644 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-13 12:43:03,334 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $142.62/share
[2022-10-13 12:43:04,533 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-13 12:43:08,264 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $142.62/share
[2022-10-13 12:43:09,258 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 12:43:13,197 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ABBV at $142.5/share
[2022-10-13 12:43:14,405 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABBV ordered
[2022-10-13 12:43:18,193 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of A at $127.81/share
[2022-10-13 12:43:19,554 | tradestation:489 | INFO | MainProcess] BUY 3 shares of A ordered
[2022-10-13 12:43:23,612 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $98.98/share
[2022-10-13 12:43:24,601 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-13 12:43:28,194 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ABC at $141.89/share
[2022-10-13 12:43:29,143 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ABC ordered
[2022-10-13 12:43:32,725 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $142.61/share
[2022-10-13 12:43:33,746 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-13 12:43:37,676 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $220.7/share
[2022-10-13 12:43:38,661 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-13 12:43:42,364 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ADI at $142.48/share
[2022-10-13 12:43:43,328 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ADI ordered
[2022-10-13 12:43:47,058 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $142.63/share
[2022-10-13 12:43:48,036 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-13 12:43:51,713 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $142.5/share
[2022-10-13 12:43:52,911 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-13 12:43:56,645 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $99.0/share
[2022-10-13 12:43:57,675 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 12:44:03,172 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $220.79/share
[2022-10-13 12:44:04,466 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-13 12:44:08,230 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $142.62/share
[2022-10-13 12:44:09,244 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-13 12:44:13,025 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $98.98/share
[2022-10-13 12:44:14,202 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-13 12:44:18,013 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ADI at $142.5/share
[2022-10-13 12:44:19,003 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ADI ordered
[2022-10-13 12:44:22,514 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $142.64/share
[2022-10-13 12:44:23,683 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-13 12:44:27,200 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $220.81/share
[2022-10-13 12:44:28,213 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-13 12:44:32,012 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ADI at $142.51/share
[2022-10-13 12:44:33,256 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ADI ordered
[2022-10-13 12:44:37,260 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ABBV at $142.54/share
[2022-10-13 12:44:38,447 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABBV ordered
[2022-10-13 12:44:42,772 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $142.61/share
[2022-10-13 12:44:43,970 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-14 07:02:49,034 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:03:52,287 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:05:41,178 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:05:56,513 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:10:07,408 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:13:40,992 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:14:14,668 | requests:186 | DEBUG | MainProcess] Making request: POST https://oauth2.googleapis.com/token
[2022-10-14 07:14:19,052 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.22/share
[2022-10-14 07:14:20,791 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:14:24,776 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of A at $127.56/share
[2022-10-14 07:14:25,779 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-14 07:14:29,327 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ADI at $139.65/share
[2022-10-14 07:14:30,279 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ADI ordered
[2022-10-14 07:14:33,919 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $97.81/share
[2022-10-14 07:14:34,911 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-14 07:14:38,087 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ABC at $141.44/share
[2022-10-14 07:14:39,297 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ABC ordered
[2022-10-14 07:14:42,529 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $97.79/share
[2022-10-14 07:14:43,481 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-14 07:14:47,175 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.61/share
[2022-10-14 07:14:48,246 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:14:51,500 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $214.19/share
[2022-10-14 07:14:52,548 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-14 07:14:55,809 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $214.24/share
[2022-10-14 07:14:56,951 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:15:00,730 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.62/share
[2022-10-14 07:15:01,700 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:15:05,434 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.6/share
[2022-10-14 07:15:06,760 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:15:10,225 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.77/share
[2022-10-14 07:15:11,217 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-14 07:15:14,981 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $214.2/share
[2022-10-14 07:15:15,972 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:15:19,529 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $97.8/share
[2022-10-14 07:15:20,491 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-14 07:15:23,947 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.64/share
[2022-10-14 07:15:24,917 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:15:28,387 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $214.27/share
[2022-10-14 07:15:29,376 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-14 07:15:32,654 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.62/share
[2022-10-14 07:15:33,665 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:15:37,146 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.24/share
[2022-10-14 07:15:38,089 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:15:41,334 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of ABBV at $142.91/share
[2022-10-14 07:15:42,326 | tradestation:489 | INFO | MainProcess] BUY 3 shares of ABBV ordered
[2022-10-14 07:15:45,706 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.62/share
[2022-10-14 07:15:46,899 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:15:50,247 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.33/share
[2022-10-14 07:15:51,193 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:15:54,743 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.64/share
[2022-10-14 07:15:55,863 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:15:59,951 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.34/share
[2022-10-14 07:16:00,880 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:16:04,128 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.65/share
[2022-10-14 07:16:05,335 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:16:08,699 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $97.82/share
[2022-10-14 07:16:09,636 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-14 07:16:13,098 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.3/share
[2022-10-14 07:16:14,063 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:16:17,760 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.67/share
[2022-10-14 07:16:18,765 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:16:22,419 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.81/share
[2022-10-14 07:16:23,350 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-14 07:16:26,800 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $214.35/share
[2022-10-14 07:16:27,743 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:16:31,105 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.68/share
[2022-10-14 07:16:32,063 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:16:35,265 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.83/share
[2022-10-14 07:16:36,424 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-14 07:16:40,037 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $214.38/share
[2022-10-14 07:16:41,228 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-14 07:16:44,922 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ABBV at $143.0/share
[2022-10-14 07:16:45,956 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABBV ordered
[2022-10-14 07:16:49,564 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ADI at $139.73/share
[2022-10-14 07:16:50,495 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ADI ordered
[2022-10-14 07:16:54,150 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.33/share
[2022-10-14 07:16:55,131 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:16:58,903 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ABBV at $142.97/share
[2022-10-14 07:17:00,355 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ABBV ordered
[2022-10-14 07:17:03,735 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $140.62/share
[2022-10-14 07:17:04,699 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-14 07:17:07,852 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $97.8/share
[2022-10-14 07:17:09,011 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-14 07:17:12,181 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $97.79/share
[2022-10-14 07:17:13,191 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-14 07:17:16,581 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $214.32/share
[2022-10-14 07:17:17,739 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:17:21,156 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.61/share
[2022-10-14 07:17:22,176 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:17:25,446 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $140.54/share
[2022-10-14 07:17:26,403 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-14 07:17:29,523 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.75/share
[2022-10-14 07:17:30,579 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-14 07:17:33,827 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $214.2/share
[2022-10-14 07:17:34,822 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:17:38,214 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of ADI at $139.62/share
[2022-10-14 07:17:39,365 | tradestation:489 | INFO | MainProcess] BUY 1 shares of ADI ordered
[2022-10-14 07:17:42,886 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.51/share
[2022-10-14 07:17:43,927 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:17:47,389 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $214.12/share
[2022-10-14 07:17:48,766 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:17:52,083 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of AAPL at $140.5/share
[2022-10-14 07:17:53,240 | tradestation:489 | INFO | MainProcess] BUY 3 shares of AAPL ordered
[2022-10-14 07:17:56,629 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of GOOGL at $97.73/share
[2022-10-14 07:17:57,606 | tradestation:489 | INFO | MainProcess] BUY 2 shares of GOOGL ordered
[2022-10-14 07:18:01,101 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.51/share
[2022-10-14 07:18:02,155 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:18:05,376 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of A at $127.35/share
[2022-10-14 07:18:06,504 | tradestation:489 | INFO | MainProcess] BUY 2 shares of A ordered
[2022-10-14 07:18:09,884 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of GOOGL at $97.69/share
[2022-10-14 07:18:10,933 | tradestation:489 | INFO | MainProcess] BUY 1 shares of GOOGL ordered
[2022-10-14 07:18:14,092 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of ABBV at $142.84/share
[2022-10-14 07:18:15,131 | tradestation:489 | INFO | MainProcess] BUY 2 shares of ABBV ordered
[2022-10-14 07:18:18,513 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of AAPL at $140.5/share
[2022-10-14 07:18:19,417 | tradestation:489 | INFO | MainProcess] BUY 1 shares of AAPL ordered
[2022-10-14 07:18:22,595 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of GOOGL at $97.65/share
[2022-10-14 07:18:23,504 | tradestation:489 | INFO | MainProcess] BUY 3 shares of GOOGL ordered
[2022-10-14 07:18:26,817 | backend:459 | INFO | MainProcess] Attempting to buy 1 shares of TSLA at $213.9/share
[2022-10-14 07:18:27,956 | tradestation:489 | INFO | MainProcess] BUY 1 shares of TSLA ordered
[2022-10-14 07:18:31,151 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.46/share
[2022-10-14 07:18:32,140 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:18:35,389 | backend:459 | INFO | MainProcess] Attempting to buy 3 shares of TSLA at $213.91/share
[2022-10-14 07:18:36,377 | tradestation:489 | INFO | MainProcess] BUY 3 shares of TSLA ordered
[2022-10-14 07:18:39,703 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of AAPL at $140.47/share
[2022-10-14 07:18:40,646 | tradestation:489 | INFO | MainProcess] BUY 2 shares of AAPL ordered
[2022-10-14 07:18:44,243 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $213.96/share
[2022-10-14 07:18:45,384 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
[2022-10-14 07:18:48,592 | backend:459 | INFO | MainProcess] Attempting to buy 2 shares of TSLA at $213.9/share
[2022-10-14 07:18:49,697 | tradestation:489 | INFO | MainProcess] BUY 2 shares of TSLA ordered
